# Generated by Django 5.0.2 on 2024-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("bio", models.TextField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_update_date", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
