# Generated by Django 5.0.2 on 2024-04-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broker",
            options={"ordering": ["-id"]},
        ),
    ]
