# Generated by Django 5.0.2 on 2024-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="land_use_group",
            field=models.CharField(
                choices=[
                    ("agricultural", "Agricultural"),
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                ],
                max_length=50,
            ),
        ),
    ]
