version: '3.8'

services:

  webserver:
    build: ./webserver/
    image: ${PROJECT}/webserver:${TAG}
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - ${WEBSERVER_PORT}:80
    depends_on:
      - backend
    links:
      - backend

  postgres_db:
    image: postgres:latest
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    image: ${PROJECT}/backend:${TAG}
    env_file: ./.env
    volumes:
      - static:/app/static
      - media:/app/media
      - ./backend:/app
    depends_on:
        - postgres_db
    ports:
        - "8009:8000"
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
  static:
  media: